import { createClient } from '@supabase/supabase-js';
import { generateBrandBannerSvg } from '../src/lib/brandBannerUtils.ts';

const SUPABASE_URL = 'https://oxdywhgcdqkdxmnzlofg.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZHl3aGdjZHFrZHhtbnpsb2ZnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDU4MjkyOCwiZXhwIjoyMTA2MTU4OTI4fQ.1NWqRMe_VQnkXtlUMEscuwUvHnolwt7HWjpdJitW5Is';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const BRAND_SHOPS = [
  // 1. Fashion & Clothing Brands
  {
    id: 'brand-shop-1',
    name: 'Aarong Mymensingh',
    name_bn: 'আড়ং ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.9,
    review_count: 240,
    location: '২১ কালী শংকর গুহ রোড, নতুন বাজার মোড়, ময়মনসিংহ সদর',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '02-996669282',
    image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'বাংলাদেশের শীর্ষস্থানীয় লাইফস্টাইল ব্র্যান্ড আড়ং-এর নিজস্ব ফ্ল্যাগশিপ আউটলেট। ঐতিহ্যবাহী নকশিকাঁথা, সুতি ও সিল্কের শাড়ি, পাঞ্জাবি, শিশুদের পোশাক এবং প্রিমিয়াম হোম ডেকর।',
    opening_hours: 'সকাল ১০:০০ - রাত ৮:৩০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7562,
    longitude: 90.4035,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-2',
    name: 'ILLIYEEN Mymensingh',
    name_bn: 'ইলিয়ীন ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 175,
    location: '১ম তলা, প্রগতি টাওয়ার, ১৬ সাহেব আলী রোড, নতুন বাজার, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01805-469193',
    image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'উচ্চমানের প্রিমিয়াম ছেলেদের ফ্যাশন ব্র্যান্ড ইলিয়ীন। আধুনিক ডিজাইনের পাঞ্জাবি, কাবলি, প্রিমিয়াম শার্ট ও এক্সেসরিজ কালেকশন।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7558,
    longitude: 90.4042,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-3',
    name: 'Sailor Mymensingh',
    name_bn: 'সেইলর ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 150,
    location: '২৫/১, সুনাউল্লাহ এসপিএস টাওয়ার, কালী শংকর গুহ রোড, নতুন বাজার ট্রাফিক মোড়, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01713-028781',
    image_url: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'ইপিলিয়ন গ্রুপের জনপ্রিয় ফ্যাশন লাইফস্টাইল ব্র্যান্ড সেইলর। নারী, পুরুষ ও শিশুদের জন্য আধুনিক ক্যাজুয়াল ও ফর্মাল পোশাক।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7565,
    longitude: 90.4038,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-4',
    name: 'Twelve Clothing',
    name_bn: 'টুয়েলভ ক্লোথিং',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 130,
    location: '২৪, শ্যামাচরণ রায় রোড, নতুন বাজার, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01324-400124',
    image_url: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'ট্রেন্ডি এবং আধুনিক এথনিক ও ওয়েস্টার্ন ফ্যাশন পোশাকের ব্র্যান্ড টুয়েলভ ক্লোথিং আউটলেট।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7552,
    longitude: 90.4045,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-5',
    name: 'Richman & Lubnan',
    name_bn: 'রিচম্যান ও লুবনান',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 120,
    location: '১৩/এ, পুরোহিত পাড়া, চরপাড়া মোড়, ময়মনসিংহ সদর',
    area: 'চরপাড়া',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01678-823776',
    image_url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'ছেলেদের প্রিমিয়াম ফর্মাল ও ওয়েডিং কালেকশন। ব্লেজার, স্যুট, শেরওয়ানি, পাঞ্জাবি এবং অফিশিয়াল শার্ট-প্যান্ট।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7340,
    longitude: 90.4125,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-6',
    name: 'Gentle Park',
    name_bn: 'জেন্টল পার্ক ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 110,
    location: 'হোল্ডিং-২২ (নিচতলা), কালী শংকর গুহ রোড, নতুন বাজার মোড়, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01713-388220',
    image_url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'স্মার্ট ক্যাজুয়াল ও ফর্মাল ড্রেসিংয়ের জন্য তরুণ প্রজন্মের পছন্দের শীর্ষ ফ্যাশন ব্র্যান্ড জেন্টল পার্ক।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7560,
    longitude: 90.4039,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-7',
    name: 'Infinity Mega Mall',
    name_bn: 'ইনফিনিটি মেগা মল',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 210,
    location: '২৫ শ্যামাচরণ রায় রোড, জিলা স্কুল মোড়, নতুন বাজার, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01700-705566',
    image_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'পুরো পরিবারের কেনাকাটার সম্পূর্ণ ফ্যাশন মেগা মল। পুরুষ, নারী ও শিশুদের সব বয়সের ব্র্যান্ডেড পোশাক ও ফ্যাশন এক্সেসরিজ।',
    opening_hours: 'সকাল ৯:৩০ - রাত ৯:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7550,
    longitude: 90.4050,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-8',
    name: 'Easy Fashion',
    name_bn: 'ইজি ফ্যাশন',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 95,
    location: '৪২ সি.কে. ঘোষ রোড (মিন্টু মেমোরিয়াল কলেজের বিপরীত), ময়মনসিংহ',
    area: 'সি.কে. ঘোষ রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01711-223344',
    image_url: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'সাশ্রয়ী মূল্যে মানসম্মত ক্যাজুয়াল শার্ট, টি-শার্ট, পোলো ও গ্যাবার্ডিন প্যান্টের নির্ভরযোগ্য ব্র্যান্ড ইজি ফ্যাশন।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7528,
    longitude: 90.4055,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-9',
    name: 'BISHWORANG Mymensingh',
    name_bn: 'বিশ্ব রঙ ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 88,
    location: '৪৪/১ রামবাবু রোড, নতুন বাজার, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01730-068016',
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'বাঙালি সংস্কৃতি ও রঙের ঐতিহ্যবাহী ফিউশন ফ্যাশন হাউস বিশ্ব রঙ। এক্সক্লুসিভ শাড়ি, পাঞ্জাবি ও পারিবারিক ম্যাচিং পোশাক।',
    opening_hours: 'সকাল ১০:০০ - রাত ৮:৩০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7540,
    longitude: 90.4060,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-10',
    name: 'Artisan Mymensingh',
    name_bn: 'আর্টিসান ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 82,
    location: 'নতুন বাজার গার্ডেন সিটি (নিচ ও ১ম তলা), ২৪ নতুন বাজার মোড়, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01324-738905',
    image_url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'এক্সক্লুসিভ ফ্যাশন ও ট্রেন্ডি পোশাক কালেকশন নিয়ে গার্ডেন সিটিতে অবস্থিত আধুনিক আর্টিসান আউটলেট।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7555,
    longitude: 90.4048,
    updated_at: new Date().toISOString()
  },

  // 2. Footwear Brands
  {
    id: 'brand-shop-11',
    name: 'Bata Showroom - Palika Shopping Centre',
    name_bn: 'বাটা শোরুম - পালিকা শপিং সেন্টার',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 190,
    location: 'পালিকা শপিং সেন্টার, স্টেশন রোড, ময়মনসিংহ সদর',
    area: 'স্টেশন রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01313-498241',
    image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'বিশ্বখ্যাত ফুটওয়্যার ব্র্যান্ড বাটা (Bata)-র অফিশিয়াল শোরুম। ফর্মাল জুতা, স্নিকার্স, স্যান্ডেল, লেডিস হিল ও স্কুল শু।',
    opening_hours: 'সকাল ৯:৩০ - রাত ৯:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7538,
    longitude: 90.4075,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-12',
    name: 'Bata Showroom - C.K. Ghosh Road',
    name_bn: 'বাটা শোরুম - সি.কে. ঘোষ রোড',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 160,
    location: 'সি.কে. ঘোষ রোড, ময়মনসিংহ সদর',
    area: 'সি.কে. ঘোষ রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01313-498251',
    image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'সি.কে. ঘোষ রোডের কেন্দ্রস্থলে অবস্থিত বাটার সুবিশাল শোরুম। লেদার জুতা ও ব্যাগ কালেকশন।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7522,
    longitude: 90.4052,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-13',
    name: 'Bata Showroom - Ganginarpar',
    name_bn: 'বাটা শোরুম - গাঙিনারপাড়',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 140,
    location: 'গাঙিনারপাড় মোড়, ময়মনসিংহ সদর',
    area: 'গাঙিনারপাড়',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01313-498240',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'গাঙিনারপাড় প্রধান বাণিজ্যিক মোড়ে অবস্থিত বাটা ফুটওয়্যার ও এক্সেসরিজ স্টোর।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7512,
    longitude: 90.4068,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-14',
    name: 'Bata Showroom - Charpara',
    name_bn: 'বাটা শোরুম - চরপাড়া',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 125,
    location: 'চরপাড়া মোড়, মেডিকেল কলেজ রোড, ময়মনসিংহ সদর',
    area: 'চরপাড়া',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01313-498249',
    image_url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'চরপাড়া মোড় ও মেডিকেল সংলগ্ন এলাকার গ্রাহকদের জন্য বাটার পূর্ণাঙ্গ আধুনিক শো-রুম।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7345,
    longitude: 90.4120,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-15',
    name: 'Apex Footwear',
    name_bn: 'এপেক্স ফুটওয়্যার ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 185,
    location: 'কুলসুম পপি ভবন, ১১ সি.কে. ঘোষ রোড, ময়মনসিংহ সদর',
    area: 'সি.কে. ঘোষ রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01700-705151',
    image_url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'বাংলাদেশের শীর্ষস্থানীয় জেনুইন লেদার জুতার ব্র্যান্ড এপেক্স (Apex)-এর নিজস্ব আউটলেট। ভেনচুরা, নিনো রসি, স্প্রিন্ট স্পোর্টস শু ও লেদার সামগ্রী।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7524,
    longitude: 90.4054,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-16',
    name: 'Lotto Showroom Mymensingh',
    name_bn: 'লোটো শোরুম ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 135,
    location: 'গাঙিনারপাড় প্রধান সড়ক, ময়মনসিংহ সদর',
    area: 'গাঙিনারপাড়',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01711-889922',
    image_url: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'ইতালীয় স্পোর্টস ব্র্যান্ড লোটো (Lotto)-র অফিশিয়াল জুতা, কেডস, স্নিকার্স, স্পোর্টস ট্রাউজার ও টি-শার্ট।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7516,
    longitude: 90.4062,
    updated_at: new Date().toISOString()
  },

  // 3. Electronics & Home Appliance Brands
  {
    id: 'brand-shop-17',
    name: 'Walton Plaza - Mymensingh',
    name_bn: 'ওয়ালটন প্লাজা - নতুন বাজার',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 220,
    location: '৩৮, রামবাবু রোড (বিদ্যাপীঠ স্কুলের পশ্চিম পাশে), নতুন বাজার, ময়মনসিংহ',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01678-028087',
    image_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'ওয়ালটন কোম্পানির নিজস্ব মেগা শোরুম। ফ্রিজ, এলইডি টিভি, এসি, ওয়াশিং মেশিন, ব্লেন্ডার, স্মার্টফোন ও হোম অ্যাপ্লায়েন্স সহজ কিস্তিতে বিক্রয়।',
    opening_hours: 'সকাল ৯:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7545,
    longitude: 90.4065,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-18',
    name: 'Singer Bangladesh Showroom',
    name_bn: 'সিঙ্গার বাংলাদেশ শোরুম ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 145,
    location: 'নিচতলা, ৮ আর. কে. মিশন রোড, ময়মনসিংহ সদর',
    area: 'আর কে মিশন রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01713-245678',
    image_url: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'আন্তর্জাতিক ব্র্যান্ড সিঙ্গার-এর ইলেকট্রনিক্স শো-রুম। সিঙ্গার রেফ্রিজারেটর, সেলাই মেশিন, রঙিন টিভি, মাইক্রোওয়েভ ওভেনের অফিসিয়াল ওয়ারেন্টি সেবা।',
    opening_hours: 'সকাল ৯:৩০ - রাত ৮:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7570,
    longitude: 90.4020,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-19',
    name: 'LG-Butterfly Showroom',
    name_bn: 'এলজি-বাটারফ্লাই শোরুম ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 130,
    location: '১১, সিটি সেন্টার (২য় তলা), রামবাবু রোড, অলকা নদী বাংলার বিপরীত, ময়মনসিংহ',
    area: 'রামবাবু রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01716-989878',
    image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'এলজি বাটারফ্লাই অফিশিয়াল ইলেকট্রনিক্স ও হোম অ্যাপ্লায়েন্স শোরুম। এলজি ওভিসি টিভি, স্মার্ট ইনভার্টার এসি ও ফ্রিজের বিশ্বস্ত বিক্রয়কেন্দ্র।',
    opening_hours: 'সকাল ১০:০০ - রাত ৯:০০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7535,
    longitude: 90.4068,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-20',
    name: 'Samsung Smart Plaza',
    name_bn: 'স্যামসাং স্মার্ট প্লাজা',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 215,
    location: 'দোকান ১, ৮ ও ৯, হোল্ডিং ৯৬, সি.কে. ঘোষ রোড, প্রেস ক্লাব মার্কেট, ময়মনসিংহ',
    area: 'প্রেস ক্লাব মার্কেট',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01730-058899',
    image_url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'স্যামসাং অনুমোদিত অথরাইজড স্মার্ট প্লাজা। স্যামসাং গ্যালাক্সি মোবাইল, ট্যাব, গ্যালাক্সি ওয়াচ, বাডস এবং অফিশিয়াল অ্যাক্সেসরিজ।',
    opening_hours: 'সকাল ১০:০০ - রাত ৮:৩০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7527,
    longitude: 90.4053,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-21',
    name: 'RFL Best Buy',
    name_bn: 'আরএফএল বেস্ট বাই ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.6,
    review_count: 140,
    location: '৩৩/এ, ১ম তলা, সি.কে. ঘোষ রোড, ময়মনসিংহ সদর',
    area: 'সি.কে. ঘোষ রোড',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '09613-737777',
    image_url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'গৃহস্থালি প্লাস্টিক পণ্য, মেলামাইন, কিচেন ওয়্যার, স্টোভ এবং ইলেকট্রনিক্স সামগ্রীর একমাত্র সমন্বিত সুপার রিটেল আউটলেট।',
    opening_hours: 'সকাল ৯:০০ - রাত ৯:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7523,
    longitude: 90.4056,
    updated_at: new Date().toISOString()
  },

  // 4. Superstores & Jewelry Brands
  {
    id: 'brand-shop-22',
    name: 'Agora Super Shop',
    name_bn: 'আগোরা সুপার শপ ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.8,
    review_count: 195,
    location: 'মুনা টাওয়ার, ৬ সাহেব আলী রোড, নতুন বাজার, ময়মনসিংহ সদর',
    area: 'নতুন বাজার',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '09613-882288',
    image_url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'বাংলাদেশের প্রথম সুপারমার্কেট চেইন আগোরার ময়মনসিংহ শাখা। সতেজ মাছ, মাংস, দেশি-বিদেশি গ্রোসারি পণ্য, কসমেটিকস ও বেকারি পণ্য।',
    opening_hours: 'সকাল ৮:০০ - রাত ১০:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7554,
    longitude: 90.4046,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-23',
    name: 'Shwapno Super Shop',
    name_bn: 'স্বপ্ন সুপার শপ ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.7,
    review_count: 180,
    location: 'চরপাড়া মোড়, মেডিকেল কলেজ রোড, ময়মনসিংহ সদর',
    area: 'চরপাড়া',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01755-667788',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'এসিআই লজিস্টিকসের জনপ্রিয় রিটেল চেইন স্বপ্ন। দৈনন্দিন বাজারের সেরা অফার ও শতভাগ নিরাপদ খাদ্যপণ্য ও গ্রোসারি।',
    opening_hours: 'সকাল ৮:০০ - রাত ১০:০০',
    price_range: '৳৳',
    is_featured: true,
    latitude: 24.7335,
    longitude: 90.4128,
    updated_at: new Date().toISOString()
  },
  {
    id: 'brand-shop-24',
    name: 'Diamond World Mymensingh',
    name_bn: 'ডায়মন্ড ওয়ার্ল্ড ময়মনসিংহ',
    category: 'Shopping',
    category_id: 'cat-8',
    category_slug: 'shopping',
    rating: 4.9,
    review_count: 155,
    location: 'অলকা নদী বাংলা কমপ্লেক্স, গোল্ড মার্কেট, ৪ রামবাবু রোড, গাঙিনারপাড়, ময়মনসিংহ',
    area: 'গাঙিনারপাড়',
    district: 'ময়মনসিংহ',
    upazila: 'ময়মনসিংহ সদর',
    phone: '01713-199277',
    image_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
    gallery_images: [],
    description: 'আন্তর্জাতিক মান সনদপ্রাপ্ত ডায়মন্ড ও স্বর্ণের অলংকার নির্মাতা প্রতিষ্ঠান ডায়মন্ড ওয়ার্ল্ড-এর এক্সক্লুসিভ শোরুম। বিয়ের গহনা ও ডায়মন্ড রিং।',
    opening_hours: 'সকাল ১০:৩০ - রাত ৮:৩০',
    price_range: '৳৳৳',
    is_featured: true,
    latitude: 24.7521,
    longitude: 90.4066,
    updated_at: new Date().toISOString()
  }
];

async function seed() {
  console.log(`Seeding ${BRAND_SHOPS.length} top brand shops in Mymensingh...`);
  for (const shop of BRAND_SHOPS) {
    shop.image_url = generateBrandBannerSvg(
      shop.name_bn,
      shop.name,
      shop.category,
      shop.location,
      shop.phone
    );
    const { error } = await supabase.from('businesses').upsert(shop, { onConflict: 'id' });
    if (error) {
      console.error(`Error inserting ${shop.name}:`, error);
    } else {
      console.log(`✓ Inserted brand shop: ${shop.name_bn} (${shop.area})`);
    }
  }

  console.log('Seeding of brand shops complete.');
}

seed();
